"""Morning briefing — fires at 7am local, daily, weekdays.

Generates `output/daemon/briefings/YYYY-MM-DD-morning.md` with:
  • Overdue commitments
  • Due today + due this week
  • Stale wiki pages worth refreshing
  • Top 3 people you haven't touched in a while

Slack/email delivery comes when connectors land. For now, the briefing
file is the artifact — the user reads it, or a future hook pushes it.
"""

from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from secondbrain.core import work_items
from secondbrain.core.wiki import list_pages, read_page
from secondbrain.core.workspace import Workspace
from secondbrain.daemon.registry import Job, register_job


def _build_briefing(ws: Workspace) -> dict[str, Any]:
    """Build the briefing payload. Pure function — easy to test."""
    today_date = date.today()
    today = today_date.isoformat()
    week_cutoff = (today_date + timedelta(days=7)).isoformat()

    overdue: list[dict] = []
    today_items: list[dict] = []
    week_items: list[dict] = []

    if ws.db_path.exists():
        conn = ws.open_db()
        work_items.ensure_schema(conn)
        rows = work_items.query(conn, item_type="action", status="open", limit=200)
        for r in rows:
            due = r.get("due_date") or ""
            if not due:
                continue
            if due < today:
                overdue.append(r)
            elif due == today:
                today_items.append(r)
            elif today < due <= week_cutoff:
                week_items.append(r)

    # Stale people pages (no update in 30+ days)
    stale_cutoff = (today_date - timedelta(days=30)).isoformat()
    quiet_people: list[dict] = []
    for page in list_pages(ws.wiki_root, "people"):
        raw = page.frontmatter.get("last_updated")
        # YAML may parse '2026-04-04' as a `date` object — coerce to ISO string.
        if hasattr(raw, "isoformat"):
            last_updated = raw.isoformat()
        elif raw is None:
            last_updated = ""
        else:
            last_updated = str(raw)
        trust = page.frontmatter.get("trust_tier") or ""
        # Focus quiet-relationship surfacing on trusted/inner-circle people
        if last_updated and last_updated < stale_cutoff and trust in ("trusted", "inner-circle"):
            quiet_people.append({
                "slug": page.slug,
                "name": page.frontmatter.get("title"),
                "last_updated": last_updated,
                "trust_tier": trust,
            })

    return {
        "as_of": today,
        "overdue": overdue,
        "due_today": today_items,
        "due_this_week": week_items,
        "quiet_relationships": quiet_people[:3],
    }


def _render_markdown(payload: dict[str, Any]) -> str:
    lines: list[str] = [
        f"# Morning briefing — {payload['as_of']}",
        "",
        f"_Auto-generated by `sb daemon` at {datetime.now().strftime('%H:%M %Z')}_",
        "",
    ]

    if payload["overdue"]:
        lines.append(f"## Overdue ({len(payload['overdue'])})")
        lines.append("")
        for r in payload["overdue"][:10]:
            owner = r.get("owner") or "—"
            due = r.get("due_date") or "—"
            lines.append(f"- **[{r['id']}] {r['title']}**")
            lines.append(f"  - owner: {owner} | due: {due}")
        lines.append("")
    else:
        lines.append("## Overdue\n\n_None — nice._\n")

    if payload["due_today"]:
        lines.append(f"## Due today ({len(payload['due_today'])})")
        lines.append("")
        for r in payload["due_today"]:
            owner = r.get("owner") or "—"
            lines.append(f"- [ ] [{r['id']}] {r['title']} ({owner})")
        lines.append("")

    if payload["due_this_week"]:
        lines.append(f"## Due this week ({len(payload['due_this_week'])})")
        lines.append("")
        for r in payload["due_this_week"]:
            owner = r.get("owner") or "—"
            due = r.get("due_date") or "—"
            lines.append(f"- [ ] [{r['id']}] {r['title']} ({owner}, due {due})")
        lines.append("")

    if payload["quiet_relationships"]:
        lines.append("## Quiet relationships (30+ days)")
        lines.append("")
        for p in payload["quiet_relationships"]:
            lines.append(f"- **{p['name']}** ({p['trust_tier']}) — last seen {p['last_updated']}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("_To dismiss a job permanently: `sb daemon disable morning_brief`_")
    return "\n".join(lines)


def run(ws: Workspace) -> dict[str, Any]:
    """Job entry point. Builds + writes the briefing file.

    Delivery: writes to output/daemon/briefings/{date}-morning.md. To get the
    briefing into Slack, ask Claude in a Cowork session: "Post today's morning
    briefing to my Slack DM" — Claude uses its built-in Slack connector
    (already authenticated via Claude Desktop Settings → Connectors). No need
    to register a separate Slack app or paste a token.
    """
    payload = _build_briefing(ws)
    md = _render_markdown(payload)

    out_dir = ws.project_home / "output" / "daemon" / "briefings"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{payload['as_of']}-morning.md"
    out_file.write_text(md, encoding="utf-8")

    return {
        "path": str(out_file.relative_to(ws.project_home)),
        "overdue": len(payload["overdue"]),
        "due_today": len(payload["due_today"]),
        "due_this_week": len(payload["due_this_week"]),
        "quiet_relationships": len(payload["quiet_relationships"]),
    }


register_job(Job(
    id="morning_brief",
    description="Daily 7am briefing — overdue + due-today + due-this-week + quiet relationships",
    schedule={"cron": {"day_of_week": "mon-fri", "hour": 7, "minute": 0}},
    run=run,
    enabled_default=True,
))
